# Generated by Django 3.1.7 on 2021-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0004_auto_20211125_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinnhan',
            name='content',
        ),
        migrations.AddField(
            model_name='tinnhan',
            name='messenge',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='tinnhan',
            name='messenger',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
