# Generated by Django 3.1.7 on 2021-12-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0006_auto_20211206_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinnhan',
            old_name='nguoigui',
            new_name='noidung',
        ),
    ]
